### PR TITLE
Don't build template-haskell-optics on GHC 8.8

### PR DESCRIPTION
**Pull request by adamgundry**
Hopefully this might help with #195.

### CODE REVIEW

**Comment by arybczak** [comment]
I fixed tests, but doctest still fails.

**Comment by adamgundry** [comment]
Thanks. I stopped doctest looking at `template-haskell-optics` (there aren't any anyway) and now the build is green on 8.8.1, so I've tweaked the CI config to no longer allow failures.

**Comment by adamgundry** [comment]
The build has passed according to Travis, so I'm not sure why this isn't showing on GitHub.

**Comment by arybczak** [comment]
Yes, I've seen that, it's a bit weird. I'm going to rerun it after merging the other PRs.

**Pull request merged**
