### PR TITLE
Add ifst and isnd

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by phadej** [comment]
The name focus comes from

```haskell
-- (Actually, AffineTraversable, and Traversable1 would be more right superclasses, if also existed).
class Traversable t => Singleton t where
    focus :: Functor f => (a -> f b) -> t a -> f (t b)
```

A name I invented just today, so I'm not (yet) attached to it.

https://oleg.fi/gists/posts/2018-05-12-singleton-container.html uses `peekaboo` :)

**Comment by arybczak** [comment]
`ifocus` is a very generic name :thinking: I take it `lens` doesn't have this?

**Comment by phadej** [comment]
`ifst` and `isnd` would make sense. (`first` is slightly too overloaded). Also they are about as short as `_1` and `_2`.

**Comment by arybczak** [comment]
Sounds good :+1:

**Review by arybczak — APPROVED** [review]

**Comment by phadej** [comment]
@adamgundry are you fine with this?

**Review by adamgundry — APPROVED** [review]
Seems fine to me. Sorry for the latency.

**Comment by phadej** [comment]
@adamgundry no worries. As long as you find time to discuss *breaking changes*, there is no problem delaying things like this. :)

**Pull request merged**
