### PR TITLE
Run doctest on Travis CI

### PR DESCRIPTION
**Pull request by adamgundry**

### CODE REVIEW

**Comment by arybczak** [comment]
It looks like these don't run:

```
$ doctest --fast $(find generic-optics/src optics/src optics-core/src optics-extra/src optics-sop/src optics-th/src optics-vl/src -name '*.hs') -XBangPatterns -XDefaultSignatures -XFlexibleContexts -XFlexibleInstances -XFunctionalDependencies -XDeriveFunctor -XGADTs -XLambdaCase -XMultiParamTypeClasses -XRankNTypes -XScopedTypeVariables -XTupleSections -XTypeFamilies -XTypeOperators -XDataKinds -XTypeApplications -XInstanceSigs
find: ‘generic-optics/src’: No such file or directory
find: ‘optics/src’: No such file or directory
find: ‘optics-core/src’: No such file or directory
find: ‘optics-extra/src’: No such file or directory
find: ‘optics-sop/src’: No such file or directory
find: ‘optics-th/src’: No such file or directory
find: ‘optics-vl/src’: No such file or directory
Loaded package environment from /tmp/dist-test.2PUc/.ghc.environment.x86_64-linux-8.6.5
Loaded package environment from /tmp/dist-test.2PUc/.ghc.environment.x86_64-linux-8.6.5
Examples: 0  Tried: 0  Errors: 0  Failures: 0
```

**Comment by adamgundry** [comment]
Argh, there was me feeling happy that I'd got CI to pass. :cry: I'll take a closer look at the script.

**Comment by arybczak** [comment]
I fixed the remaining issues.

**Comment by adamgundry** [comment]
Hurrah, thanks for finishing this off. :smile:

**Pull request merged**
