### PR TITLE
Add non, non' and anon

### LINKED ISSUE #238: Is there an equivalent to 'non' from lens?
Thanks for this library, I'm really excited about it! I'm just starting to explore and tentatively see if I can convert some of my `lens`-using code to `optics`.

There's one place where I use [non](https://hackage.haskell.org/package/lens-4.17.1/docs/Control-Lens-Iso.html#v:non) with a `Map`, just like the examples in the lens documentation. I'm not finding any corresponding `Iso` in optics. I imagine it would look something like this:

```haskell
non :: Eq a => a -> Iso' (Maybe a) a
non z = iso f g
  where
    g x | x == z     =  Nothing
        | otherwise  =  Just x

    f Nothing   =  z
    f (Just x)  =  x
```

Was this an intentional omission because `non` (as noted in the lens docs) is not a true isomorphism? Is there another way to achieve the same effect with optics?

### PR DESCRIPTION
**Pull request by arybczak**
Fixes #238 - I'm not sure if we want to have `non'` and `anon` though, they feel a bit weird to me. Any opinions?

### CODE REVIEW

**Comment by arybczak** [comment]
Ok, so

```haskell
non = non' . only
anon = non' . nearly
```

Maybe it makes sense to only include `non'` (and rename it to `non`) then?

**Comment by chris-martin** [comment]
Would it make sense to also add the documentation regarding the `Map` use cases to `Data.Map.Optics` to aid discoverability?

**Comment by chris-martin** [comment]
> Maybe it makes sense to only include `non'` (and rename it to `non`) then?

That seems sensible to me.

Practically, given the one use case I know: instead of writing `non mempty`, one would write `non _Empty`, which is about the same.

Pedagogically, I like reducing the number of functions, or at least emphasizing which one is the most "fundamental" of them (which the name `non'` fails to do), and I really appreciate a function that converts a `Prism` to an `Iso` because it lets me keep my thoughts contained within the optics family.

**Comment by adamgundry** [comment]
> Maybe it makes sense to only include `non'` (and rename it to `non`) then?

In cases like this I'd be inclined to retain the `lens` terminology rather than introducing small differences in pursuit of some minimal subset. Of course we won't be perfectly compatible with `lens`, but having `non`, `non'` and `anon` feels reasonable to me.

**Comment by arybczak** [comment]
> Would it make sense to also add the documentation regarding the Map use cases to Data.Map.Optics to aid discoverability?

I think it would. If you have something specific in mind, please make a PR :)

I'm gonna merge this if there are no objections.

**Comment by arybczak** [comment]
I added a changelog.

**Pull request merged**
