### PR TITLE
Make generation of LabelOptic instances aware of injective type families  and polymorphic kinds

### PR DESCRIPTION
**Pull request by arybczak**
Existing check wasn't taking injective type families into account (and wasn't working properly really).

### CODE REVIEW

**Comment by arybczak** [comment]
@adamgundry looks like with type-changing updates we also have to worry about changing kinds, though it seemed easy enough to handle here :thinking:

**Comment by phadej** [comment]
@arybczak isn't it that when you write those by hand, the kind variables are usually implicitly quantified so one doesn't really worry?

Related to kinds, @arybczak have you noted https://github.com/ekmett/lens/issues/917, does `optics-th` has the same problem?

**Comment by arybczak** [comment]
> @arybczak isn't it that when you write those by hand, the kind variables are usually implicitly quantified so one doesn't really worry?

I'm not sure what you mean.

> Related to kinds, @arybczak have you noticed [ekmett/lens#917](https://github.com/ekmett/lens/issues/917), does `optics-th` have the same problem?

Yes, mostly. The example from the first post works when you replace `makePrisms` with `makePrismLabels`, but the rest fails.

**Comment by phadej** [comment]
> > @arybczak isn't it that when you write those by hand, the kind variables are usually implicitly quantified so one doesn't really worry?
> 
> I'm not sure what you mean.

```haskell
{-# LANGUAGE DataKinds             #-}
{-# LANGUAGE FlexibleInstances     #-}
{-# LANGUAGE GADTs                 #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedLabels      #-}
{-# LANGUAGE PolyKinds             #-}
{-# LANGUAGE UndecidableInstances  #-}

import           Data.Proxy
import           GHC.TypeLits
import           Optics.Core

instance (k ~ An_Iso, u ~ Proxy a, v ~ Proxy b) => LabelOptic "proxy" k (Proxy a) (Proxy b) u v where
    labelOptic = iso (const Proxy) (const Proxy)


proxy5 :: Proxy 5
proxy5 = Proxy

proxyFoo :: Proxy "foo"
proxyFoo = proxy5 & #proxy .~ Proxy
```

Here the instance is polykinded, isn't it?

If I write

```haskell
instance (k ~ An_Iso, u ~ Proxy a, v ~ Proxy b) => LabelOptic "proxy" k (Proxy (a :: ak)) (Proxy (b :: ak)) u v where
```

an example doesn't compile. 

If I write

```haskell
instance (k ~ An_Iso, u ~ Proxy a, v ~ Proxy b) => LabelOptic "proxy" k (Proxy (a :: ak)) (Proxy (b :: bk)) u v where
```

Then it does again.

I actually don't know which would be better, first or last (implicit or explicit). The same question as in lens 917.

**Comment by arybczak** [comment]
Right. I still don't know how that relates to what's in the PR :) You mean type signatures in tests? I've written them explicitly with changing kinds to make it easier to see what's going on.

**Comment by phadej** [comment]
It doesn't relate to this PR, it was more a comment along lines: "if we can change types, then changing kinds shouldn't be much more difficult - if at all"

**Comment by adamgundry** [comment]
This looks like a step in the right direction to me.

Thinking about it, I came up with this example:
```hs
data FamRec8 k a = FamRec8
  { _famRec8Thing :: Proxy (a :: k)
  }
makeFieldLabels ''FamRec8
```
which generates
```hs
instance forall a1 k (a2 :: k) b (a3 :: k).
         (a1 ~ Proxy a2, b ~ Proxy a3) =>
         LabelOptic "thing" An_Iso (FamRec8 k a2) (FamRec8 k a3) a1 b
```
but this doesn't permit kind-changing, when it could, because the manually written instance is accepted:
```hs
instance (u ~ Proxy a, v ~ Proxy b) => LabelOptic "thing" An_Iso (FamRec8 k a) (FamRec8 l b) u v where
  labelOptic = iso _famRec8Thing FamRec8
```

**Comment by arybczak** [comment]
Interesting. Looks like TH doesn't give enough information to do that.

Within TH
```haskell
data FamRec8 k a = FamRec8
  { _famRec8Thing :: Proxy (a :: k)
  }
```
and
```haskell
data FamRec8 k a = FamRec8
  { _famRec8Thing :: Proxy a
  }
```
are indistinguishable :confused: And in the second case `k` is a phantom type.

**Comment by phadej** [comment]
What TH tells about:

```haskell
data FamRec8 k (a :: k) = FamRec8
  { _famRec8Thing :: Proxy a
  }
```

**Comment by arybczak** [comment]
Never mind, it required a bit of gymnastics, but is supported now.

I also made the first example from ekmett/lens#917 compile. Other ones are a bit more tricky, but also can be fixed.

**Comment by arybczak** [comment]
Now all examples from ekmett/lens#917 work :+1:

**Comment by arybczak** [comment]
Ok, it's ready to be merged. Changes:
1) TH generated `LabelOptic` instances for field optics work properly in presence of type families
2) Improved support for TH generated optics in presence of kind polymorphism
3) Fixed calculation of phantom types in TH generation of `LabelOptic` prism instances

**Pull request merged**
