### PR TITLE
Make use like view, without ViewResult

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by arybczak** [comment]
How about adding a version for traversals called `multiuse`?

**Comment by phadej** [comment]
I think that `asks $ toListOf someTraversal` (or `gets`) is not that bad.

I wouldn't hold this going in just because there is no good name.

**Comment by phadej** [comment]
For the record, I'm against editing changelogs in PRs. They conflict.

**Comment by phadej** [comment]
And looks like there isn't Changelog file in `optics-extra`, so the one making release, please remember this PR. 

cc @adamgundry

**Comment by arybczak** [comment]
> please remember this PR

Yeah, that's why changelog changes need to be made in PRs 😞

**Comment by phadej** [comment]
@arybczak if you are willing to resolve conflicts in my (and others') PR, then we can write that (i.e. add entry to changelog, **we** will resolve conflicts before merging) into `CONTRIBUTING.md`

**Comment by arybczak** [comment]
Fair enough ;)

**Pull request merged**
