### PR TITLE
Add simpleFieldLabels and simpleNamer

### PR DESCRIPTION
**Pull request by arybczak**

### CODE REVIEW

**Comment by arybczak** [comment]
I'm not sure if `simple{FieldLabels,Namer}` is a good name. Perhaps `noPrefix{FieldLabels,Namer}` would be better?

**Comment by phadej** [comment]
@adamgundry as a native speaker could comment :) I'd go with something like `directNamer`, `intactNamer` or `pristineNamer` (again, I'm not 100% about nuance differences these might have).

**Comment by arybczak** [comment]
@adamgundry ping :)

**Comment by adamgundry** [comment]
Sorry for being slow (on this and other things), I've just been snowed under.

Given that we have `underscoreNoPrefixNamer` and `classUnderscoreNoPrefixNamer` I'm somewhat inclined towards `noPrefixNamer`/`noPrefixFields`. I think various synonyms for "unchanging" work in a `...Namer` context (`identityNamer`?), but for `...Fields` something like `identityFields` or `pristineFields` seems more confusing as it doesn't clearly refer to the names.

Presumably this doesn't generate top-level lens definitions with the same name as the selector functions, though? How does that work?

**Comment by arybczak** [comment]
> Presumably this doesn't generate top-level lens definitions with the same name as the selector functions, though? How does that work?

It doesn't, i.e. if you try to use it with `makeLensesWith`, you'll get compilation errors (multiple declarations of ...) (`declateLensesWith` works). It's supposed to be used for generation of OpticLabel instances.

**Comment by arybczak** [comment]
I changed `simple` to `noPrefix`.

**Pull request merged**
