### PR TITLE
WIP: filtered is AffineFold

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by arybczak** [comment]
Looks good.

Let's replace `filtered` from `Optics.Fold` with this one.

BTW, they are combinators simply because you can't write `ifiltered` in the other form as you don't have access to the index, so I made `filtered` have the same form for consistency.

As a bonus, I'm pretty sure that if `unsafeFiltered` is a combinator, you can precisely write when it's a valid traversal.

**Comment by arybczak** [comment]
Oh wait, I didn't actually notice that you moved away from the combinator style. Right, so I'd like to preserve it for reasons mentioned above.

**Comment by adamgundry** [comment]
I don't have a strong opinion on combinator vs compositional style, as I haven't thought about the problem, but if we end up keeping the combinator style we should document the divergence from `lens`.

**Comment by phadej** [comment]
For the record: I tried to make machinery to make `ifiltered`-like combinators be definable "inline", i.e. I tried to make following possible to write

```haskell
myfold = ifolded %? ifiltered (\i a -> ...)
```

1. it requires making `%` **infixl** (which I think we *should do* that)
2. adding new type: `OpticIxTransformer k is js s t a b` (note the `js`)
    - handwavy intuition: `Optic` *is* `OpticIxTransformer` which may only add indices, ~`Monoid`: `Optic is ~ forall js. OpticIxTransformer js (is ++ js)`. The restrictiveness of current `Optic` **is** good thing, but there are (e.g. `ifiltered`) where it's unfortunate.
3. but unfortunately the current machinery (= implementation of indices) resisted this frankly
    - I will try slightly different implementation as an "research" experiment, but I don't suggest changing what we have now.

Even unsuccessful, this small exercise made me want `%` and `%%` to be `infixl`; that's how I read the optics composition already, and optic-transformer-not-combinator `ifiltered` would work. It cannot be pre-composed. We'd want following operators (below) and `%%?` **is not** associative, which suggest "correct" associativity for `%%`.

```haskell
(%%)  :: Optic k is s t u v -> Optic              k    js u v a b -> Optic k (is ++ js) s t a b
(%%?) :: Optic k is s t u v -> OpticIxTransformer k is js u v a b -> Optic k        js  s t a b
```
```

**Comment by arybczak** [comment]
:+1: for making `%` infixl. I think we should just do it as it's more natural and nobody objected to the idea in #20 . Would you mind creating a PR for that?

**Comment by arybczak** [comment]
Since `ifiltered` can't be made an affine fold, let's close this.

**Pull request closed without merging**
