### PR TITLE
Drop support for GHC 8.0.2 and add 'both'

### PR DESCRIPTION
**Pull request by arybczak**
PR to test waters, but it looks like it simplifies things quite a lot.

### CODE REVIEW

**Comment by adamgundry** [comment]
I'm in two minds about this... on the one hand I can see that it makes things a fair bit simpler. On the other, I've been trying out `optics` on a project that currently still needs to support 8.0.2.

**Comment by arybczak** [comment]
Was the tryout successful? ;)

**Comment by adamgundry** [comment]
Broadly successful in that I got the library to compile with `optics` without needing much more than mechanical changes. I did come across a few missing pieces on which my code relies, which are currently stubbed out and raised as issues (#30, #103).

**Comment by arybczak** [comment]
Alright, let's keep the compatibility for now. it's not a big deal.

**Pull request closed without merging**
