### PR TITLE
Implement Mapping using roam

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by arybczak** [comment]
Can you explain the motivation behind these?

**Comment by phadej** [comment]
`map'` -> `roam`:

- Main motivation is `inspection-testing`; with definition using `map'`; the computation nrule doesn't hold. (I I read the core right, using `Context` made something stricter)
- It's consistent with `Traversing` wander

Adding `linear` is similar motivation, including that conversion from van Laarhoven representation doesn't involve `Context` (in most cases).

**Comment by arybczak** [comment]
Ok. Can you make the utility function for one particular definition of `linear` that's repeated 4 times?

**Comment by arybczak** [comment]
Also INLINE is missing on iroam definitions.

**Comment by phadej** [comment]
> Ok. Can you make the utility function for one particular definition of linear that's repeated 4 times?

Is it ok to make default implementation?

**Pull request merged**
